/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mini_project;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Baruni Priya T S
 */
public class City_selection extends javax.swing.JFrame {
    String amount;
    /**
     * Creates new form City_selection
     */
    public City_selection() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public City_selection(String username,String amount) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        jLabel4.setText(username);
        this.amount=amount;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("City_selection");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Baruni Details\\sem 3\\oops\\Mini project details\\seed.png")); // NOI18N
        jLabel1.setText("jLabel1");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Exam Form 2020");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 0));
        jLabel3.setText("City selection :");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1339, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("First preference :");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel6.setText("Select State :");

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal", "Andaman and Nicobar islands", "Chandigarh", "Daman and Diu", "Delhi", "Jammu and Kashmir", "Ladakh", "Lakshadweep", "Puducherry " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel7.setText("Select City :");

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", " " }));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Second preference :");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel9.setText("Select State :");

        jComboBox3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal", "Andaman and Nicobar islands", "Chandigarh", "Daman and Diu", "Delhi", "Jammu and Kashmir", "Ladakh", "Lakshadweep", "Puducherry " }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel10.setText("Select City :");

        jComboBox4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("Third preference :");

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel12.setText("Select State :");

        jPanel4.setBackground(new java.awt.Color(255, 255, 102));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("If exam city choices 1 and 2 are not available, you will be alloted to this 3rd choice exam");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("city. Please choose this exam city very carefully.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBox5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal", "Andaman and Nicobar islands", "Chandigarh", "Daman and Diu", "Delhi", "Jammu and Kashmir", "Ladakh", "Lakshadweep", "Puducherry " }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel15.setText("Select City :");

        jComboBox6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Confirm and save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(158, 158, 158)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox4, 0, 275, Short.MAX_VALUE)))
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(159, 159, 159)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-30, -10, 1400, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String state = jComboBox1.getSelectedItem().toString();
        if(null!=state)
            switch (state) {
            case "None":
                JOptionPane.showMessageDialog(null,"Please select a state");
                break;
            case "Andhra Pradesh":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Anantapur", "Chittoor", "East Godavari", "Guntur", "YSR Kadapa district", "Krishna", "Kurnool", "Nellore", "Prakasam", "Srikakulam", "Vishakhapatnam", "Vizianagaram", "West Godavari" }));
                break;
            case "Arunachal Pradesh":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Tawang", "West Kameng", "East Kameng", "Pakke-Kessang", "Papum Pare", "Kurung Kumey", "Kra Daadi", "Lower Subansiri", "Upper Subansiri", "West Siang", "Shi-Yomi", "East Siang", "Siang", "Upper Siang", "Lower Siang", "Lepa-Rada", "Lower Dibang Valley", "Dibang Valley", "Anjaw", "Lohit", "Namsai", "Changlang", "Tirap", "Longding", "Kamle" }));
                break;
            case "Assam":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Baksa", "Barpeta", "Biswanath", "Bongaigaon", "Cachar", "Charaideo", "Chirang", "Darrang", "Dhemaji", "Dhubri", "Dibrugarh", "Dima Hasao", "Goalpara", "Golaghat", "Hailakandi", "Hojai", "Jorhat", "Kamrup Metropolitan", "Kamrup", "Karbi Anglong", "Karimganj", "Kokrajhar", "Lakhimpur", "Majuli", "Morigaon", "Nagaon", "Nalbari", "Sivasagar", "Sonitpur", "South Salmara-Mankachar", "Tinsukia", "Udalguri", "West Karbi Anglong" }));
                break;
            case "Bihar":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Araria", "Arwal", "Aurangabad", "Banka", "Begusarai", "Bhagalpur", "Bhojpur", "buxar", "Darbhanga", "East Champaran", "Gaya", "Gopalganj", "Jamui", "Jehanabad", "Khagaria", "Kishanganj", "Kaimur", "Katihar", "Lakhisarai", "Madhubani", "Madhepura", "Muzaffarpur", "Nalanda", "Nawada", "Patna", "Purnia", "Rohtas", "Saharsa", "Samastipur", "Sheohar", "Sheikhpura", "Saran", "Sitamarhi", "Supaul", "Siwan", "Vaishali", "West Champaran" }));
                break;
            case "Chhattisgarh":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Bijapur", "sukma", "Dantewada", "Baster", "Kondagaon", "Narayanpur", "Kanker", "Kawardha", "Rajnandgaon", "Balod", "Durg", "Bemetara", "Raipur", "Baloda Bazar", "Mahasamund", "Bilaspur", "Mungeli", "Korba", "Janjgir-Champa", "Raigarh", "Jashpur", "Korea", "Surajpur", "Surguja", "Balrampur"}));
                break;
            case "Goa":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "North goa", "South goa"}));
                break;
            case "Gujarat":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Ahmedabad", "Vadodara", "Anand", "Chhota udaipur", "Dahod", "Kheda", "Mahisagar", "Panchmahal", "Gandhinagar", "Aravalli", "Banaskantha", "Mehsana", "Patan", "Sabarkantha", "Rajkot", "Amreli", "Bhavanagar", "Botad", "Devbhoomi Dwarka", "Gir Somnath", "Jamnagar", "Junagadh", "Morbi", "Porbandar", "Surendranagar", "Kachchh"}));
                break;
            case "Haryana":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Ambala", "Bhiwani", "Charkhi Dhadri", "Faridabad", "Fatehabad", "Gurugram", "Hisar" , "Jhajjar", "Jind", "Kaithal", "Karnal", "Kurukshetra", "Mahendragarh", "Nuh", "Palwal", "Panchkula", "Panipat", "Rewari", "Rohtak", "Sirsa", "Sonipat", "Yamunanagar"}));
                break;
            case "Himachal Pradhesh":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Chamba", "Kangra", "Lahaul and Spiti", "Kullu", "Mandi", "Hamirpur", "Una", "Bilaspur", "Solan", "Sirmaur", "Shimla", "Kinnaur"}));
                break;
            case "Jammu and Kashmir":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Doda", "Jammu", "Kathua", "Kishtwar", "Poonch", "Rajouri", "Ramban", "Reasi", "Samba", "Udhampur", "Anantnag", "Bandipora", "Baramulla", "Budgam", "Ganderbal", "Kulgam", "Kupwara", "Pulwama", "Shopian", "Srinagar"}));
                break;
            case "Jharkhand":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Bokaro", "Chatra", "Deoghar", "Dhanbad", "Dumka", "East Singhbhum", "Garhwa", "Giridih", "Godda", "Gumla", "Hazaribag", "Jamtara", "Khunti", "Koderma", "Latehar", "Lohardaga", "Pakur", "Palamu", "Ramgarh", "Ranchi", "Sahibganj", "Seraikelakharsawan", "Simdega", "West Singhbhum"}));
                break;
            case "Karnataka":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Bagalkot", "Bangalore Urban", "Bangalore Rural", "Belganum", "Ballari", "Bidar", "Bijapur", "Chamarajanagar", "Chikballapur", "Chikkamagaluru", "Chitradurga", "Dakshina Kannada", "Davanagere", "Dharwad", "Gadag", "Gulbarga", "Hassan", "Haveri", "Kodagu", "Kolar", "Koppal", "Mandya", "Mysore", "Raichur", "Ramanagara", "Shimoga", "Tumkur", "Udupi", "Uttara Kannada", "Yadgir"}));
                break;
            case "Kerala":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Alappuzha", "Ernakulam", "Idukki", "Kannur", "Kasaragod", "Kollam", "Kottayam", "Kozhikode", "Malappuram", "Palakkad", "Pathanamthitta", "Thiruvananthapuram", "Thissur", "Wayanad"}));
                break;
            case "Madhya Pradhesh":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Agar Malwa", "Alirajpur", "Anuppur", "Ashoknagar", "Balaghat", "Barwani", "Betul", "Bhind", "Bhopal", "Burhanpur", "Chhatarpur", "Chhindwara", "Damoh", "Datia", "Dewas", "Dhar", "Dindori", "Guna", "Gwalior", "Harda", "Hoshangabad", "Indore", "Jabalpur", "Jhabua", "Katni", "Khandwa", "Khargone", "Mandla", "Mandsaur", "Morena", "Narsinghpur", "Neemuch", "Panna", "Raisen", "Rajgarh", "Ratlam", "Rewa", "Sagar", "Satna", "Sehore", "Seoni", "Shahdol", "Shajapur", "Sheopur", "Shivpuri", "Sidhi", "Singrauli", "Tikamgarh", "Ujjain", "Umaria", "Vidisha"}));
                break;
            case "Maharashtra":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Ahmednagar", "Akola", "Amarvati", "Aurangabad", "Beed", "Bhandara", "Buldhana", "Chandrapur", "Dhule", "Gadchiroli", "Gondia", "Hingoli", "Jalgaon", "Jalna", "Kolhapur", "Latur", "Mumbai City", "Mumbai Suburban", "Nagpur", "Nanded", "Nandurbar", "Nashik", "Osmanabad", "Palghar", "Parbhani", "Pune", "Raigad", "Ratnagiri", "Sangli", "Satara", "Sindhudurg", "Solapur", "Thane", "Wardha", "Washim", "Yavatmal"}));
                break;
            case "Manipur":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Bishnupur", "Chandel", "Churachandpur", "Imphal-East", "Imphal-West", "Senapati", "Tamenglong", "Pherzawl", "Noney", "Kamjong", "Jiribam", "Kakching"}));
                break;
            case "Meghalaya":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "West Jaintia Hills", "East Jaintia Hills", "East Khasi Hills", "West Khasi Hills", "South West Khasi Hills", "Ri-Bhoi", "North Garo Hills", "East Garo Hills", "South Garo Hills", "West Garo Hills", "South West Garo Hills"}));
                break;
            case "Mizoram":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Aizawl", "Kolasib", "Lawngtlai", "Lunglei", "Mamit", "Saiha", "Serchhip", "Champhai", "Hnahthial", "Khawzawl", "Saitual"}));
                break;
            case "Nagaland":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Dimapur", "Kiphire", "Kohima", "Longleng", "Mokokchung", "Mon", "Peren", "Phek", "Tuensang", "Wokha", "Zunheboto"}));
                break;
            case "Odisha":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Angul", "Balangir", "Balasore", "Bargarh", "Bhadrak", "Boudh", "Cuttack", "Deogarh", "Dhenkanal", "Gajapati", "Ganjam", "Jagatsinghapur", "Jaipur", "Jharsuguda", "Kalahandhi", "Kandhamal", "Kendrapara", "Kendujhar", "Khordha", "Koraput", "Malkangiri", "Mayurbhanj", "Nabarangpur", "Nayagarh", "Nuapada", "Puri", "Rayagada", "Sambalpur", "Sonepur", "Sundargarh"}));
                break;
            case "Punjab":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Amritsar", "Barnala", "Bathinda", "Faridkot", "Fatehgarh Sahib", "Fazilka", "Ferozepur", "Gurdaspur", "Hoshiarpur", "Jalandhar", "Kapurthala", "Ludhiana", "Mansa", "Mogo", "Muktsar", "Nawanshahr", "Pathankot", "Patiala", "Rupnagar", "Sahibzada Ajit Singh Nagar", "Sangrur", "Tarn Taran"}));
                break;
            case "Rajasthan":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Ajmer", "Alwar", "Banaswara", "Baran", "Barmer", "Bharatpur", "Bhilwara", "Bikaner", "Bundi", "Chittorgarh", "Churu", "Dausa", "Dholpur", "Dungarpur", "Hanumangarh", "Jaipur", "Jaisalmer", "Jalore", "Jhalawar", "Jhunjhunu", "Jodhpur", "Karauli", "Kota", "Nagaur", "Pali", "Pratapgarh", "Rajsamand", "Sawai Madhopur", "Sikar", "Sirohi", "Sri Ganganagar", "Tonk", "Udaipur"}));
                break;
            case "Sikkim":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "East Sikkim", "North Sikkim", "South Sikkim", "West Sikkim"}));
                break;
            case "Tamil Nadu":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Ariyalur", "Chengalpattu", "Chennai", "Coimbatore", "Cuddalore", "Dharmapuri", "Erode", "Kallakurichi", "Kanchipuram", "Kanyakumari", "Karur", "Krishnagiri", "Madurai", "Nagapattinam", "Namakkal", "Nilgiris", "Perambalur", "Pudukkottai", "Ramanathapuraam", "Ranipet", "Salem", "Sivaganga", "Tenkasi", "Thanjavur", "Theni", "Thoothukudi", "Tiruchirappalli", "Tirunelveli", "Tirupathur", "Tiruppur", "Tiruvallur", "Tiruvannamalai", "Tiruvarur ", "Vellore", "Viluppuram", "Virudhunagar"}));
                break;
            case "Telangana":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Adilabad", "Bhandradri Kothagudem", "Hyderabad", "Jagitial", "Jangaon", "Jayashankar Bhupalpally", "Jogulamba Gadwal", "Kamareddy", "Karimnagar", "Khamman", "Komaram Bheem", "Mahabubabad", "Mahabubnagar", "Mancherial", "Medak", "Medchal Malkajgiri", "Mulugu", "Nagarkurnool", "Narayanpet", "Nalgonda", "Nirmal", "Nizamabad", "Peddapalli", "Rajanna sircilla", "Ranga Reddy", "Sanga Reddy", "Siddipet", "Suryapet", "Vikarabad", "Wanaparthy", "Warangal Rural", "Warangal Urban", "Yadadri Bhuvanagiri"}));
                break;
            case "Tripura":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Dhalai", "Sipahijala", "Khowai", "Gomati", "Unakoti", "North Tripura", "South Tripura", "West Tripura"}));
                break;
            case "Uttar Pradesh":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Agra", "Firozabad", "Mainpuri", "Mathura", "Aligarh", "Etah", "Hathras", "Kasganj", "Allahabad", "Fatehpur", "Kaushambi", "Pratapgarh", "Azamgarh", "Ballia", "Mau", "Budaum", "Bareilly", "Pilibhit", "Shahjahanpur", "Basti", "Sant Kabir Nagar", "Siddharthnagar", "Banda", "Chitrakoot", "Hamirpur", "Mahoba", "Bahraich", "Balarampur", "Gonda", "Shravasti", "Ambedkar Nagar", "Amethi", "Barabanki", "Faizabad", "Sultanpur", "Deoria", "Gorakhpur", "Kushinagar", "Maharajganj", "Jalaun", "Jhansi", "Lalitpur", "Auraiya", "Etawah", "Farrukhabad", "Kannauj", "Kanpur Dehat", "Kanpur Nagar", "Hardoi", "Lakhimpur Kheri", "Lucknow", "Raebareli", "Sitapur", "Unnao", "Bagpat", "Bulandshahr", "Gautam Buddha Nagar", "Ghaziabad", "Hapur", "Meerut", "Bhadohi", "Mirzapur", "Sonbhadra", "Amroha", "Bijnor", "Moradabad", "Rampur", "Sambhal", "Muzaffarnagar", "Saharanpur", "Shamli", "Chandauli", "Ghazipur", "Jaunpur", "Varanasi"}));
                break;
            case "Uttarakhand":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Almora", "Bageshwar", "Chamoli", "Champawat", "Dehradun", "Haridwar", "Nainital", "Pauri Garhwal", "Pithoragarh", "Rudraprayag", "Tehri Garhwal", "Udham Singh Nagar", "Uttarkashi"}));
                break;
            case "West Bengal":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Alipurduar", "Bankura", "Birbhum", "Cooch Behar", "Dakshin Dinajpur", "Darjeeling", "Hooghly", "Howrah", "Jalpaiguri", "Jhargram", "Kalimpong", "Kolkata", "Malda", "Murshidabad", "Nadia", "North 24 parganas", "Paschim Medinipur", "Paschim Burdwan", "Purba Medinipur", "Purulia", "South 24 parganas", "Uttar Dinajpur"}));
                break;
            case "Andaman and Nicobar islands":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Nicobar", "North and Middle Andaman", "South Andaman"}));
                break;
            case "Chandigarh":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Chandigarh"}));
                break;
            case "Daman And Diu":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Daman", "Diu", "Dadra And Nagar Haveli"}));
                break;
            case "Delhi":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "New Delhi", "Central Delhi", "East Delhi", "North Delhi", "North East Delhi", "North West Delhi", "Shahdara", "South Delhi", "South East Delhi", "South West Delhi", "Weest Delhi"}));
                break;
            case "Lakshadweep":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Lakshadweep"}));
                break;
            case "Puducherry":
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Karaikal", "Mahe", "Puducherry", "Yanam"}));
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    
    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        String state = jComboBox3.getSelectedItem().toString();
        if(null!=state)
            switch (state) {
            case "None":
                JOptionPane.showMessageDialog(null,"Please select a state");
                break;
            case "Andhra Pradesh":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Anantapur", "Chittoor", "East Godavari", "Guntur", "YSR Kadapa district", "Krishna", "Kurnool", "Nellore", "Prakasam", "Srikakulam", "Vishakhapatnam", "Vizianagaram", "West Godavari" }));
                break;
            case "Arunachal Pradesh":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Tawang", "West Kameng", "East Kameng", "Pakke-Kessang", "Papum Pare", "Kurung Kumey", "Kra Daadi", "Lower Subansiri", "Upper Subansiri", "West Siang", "Shi-Yomi", "East Siang", "Siang", "Upper Siang", "Lower Siang", "Lepa-Rada", "Lower Dibang Valley", "Dibang Valley", "Anjaw", "Lohit", "Namsai", "Changlang", "Tirap", "Longding", "Kamle" }));
                break;
            case "Assam":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Baksa", "Barpeta", "Biswanath", "Bongaigaon", "Cachar", "Charaideo", "Chirang", "Darrang", "Dhemaji", "Dhubri", "Dibrugarh", "Dima Hasao", "Goalpara", "Golaghat", "Hailakandi", "Hojai", "Jorhat", "Kamrup Metropolitan", "Kamrup", "Karbi Anglong", "Karimganj", "Kokrajhar", "Lakhimpur", "Majuli", "Morigaon", "Nagaon", "Nalbari", "Sivasagar", "Sonitpur", "South Salmara-Mankachar", "Tinsukia", "Udalguri", "West Karbi Anglong" }));
                break;
            case "Bihar":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Araria", "Arwal", "Aurangabad", "Banka", "Begusarai", "Bhagalpur", "Bhojpur", "buxar", "Darbhanga", "East Champaran", "Gaya", "Gopalganj", "Jamui", "Jehanabad", "Khagaria", "Kishanganj", "Kaimur", "Katihar", "Lakhisarai", "Madhubani", "Madhepura", "Muzaffarpur", "Nalanda", "Nawada", "Patna", "Purnia", "Rohtas", "Saharsa", "Samastipur", "Sheohar", "Sheikhpura", "Saran", "Sitamarhi", "Supaul", "Siwan", "Vaishali", "West Champaran" }));
                break;
            case "Chhattisgarh":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Bijapur", "sukma", "Dantewada", "Baster", "Kondagaon", "Narayanpur", "Kanker", "Kawardha", "Rajnandgaon", "Balod", "Durg", "Bemetara", "Raipur", "Baloda Bazar", "Mahasamund", "Bilaspur", "Mungeli", "Korba", "Janjgir-Champa", "Raigarh", "Jashpur", "Korea", "Surajpur", "Surguja", "Balrampur"}));
                break;
            case "Goa":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Bicholim", "Canocona", "Cunolim", "Curchorem", "Mapusa", "Margao", "Mormugao", "Panaji", "Pernem", "Ponda", "Quepem", "Sanguem", "Sanquelim", "Valpoi"}));
                break;
            case "Gujarat":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Ahmedabad", "Vadodara", "Anand", "Chhota udaipur", "Dahod", "Kheda", "Mahisagar", "Panchmahal", "Gandhinagar", "Aravalli", "Banaskantha", "Mehsana", "Patan", "Sabarkantha", "Rajkot", "Amreli", "Bhavanagar", "Botad", "Devbhoomi Dwarka", "Gir Somnath", "Jamnagar", "Junagadh", "Morbi", "Porbandar", "Surendranagar", "Kachchh"}));
                break;
            case "Haryana":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Ambala", "Bhiwani", "Charkhi Dhadri", "Faridabad", "Fatehabad", "Gurugram", "Hisar" , "Jhajjar", "Jind", "Kaithal", "Karnal", "Kurukshetra", "Mahendragarh", "Nuh", "Palwal", "Panchkula", "Panipat", "Rewari", "Rohtak", "Sirsa", "Sonipat", "Yamunanagar"}));
                break;
            case "Himachal Pradhesh":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Chamba", "Kangra", "Lahaul and Spiti", "Kullu", "Mandi", "Hamirpur", "Una", "Bilaspur", "Solan", "Sirmaur", "Shimla", "Kinnaur"}));
                break;
            case "Jammu and Kashmir":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Doda", "Jammu", "Kathua", "Kishtwar", "Poonch", "Rajouri", "Ramban", "Reasi", "Samba", "Udhampur", "Anantnag", "Bandipora", "Baramulla", "Budgam", "Ganderbal", "Kulgam", "Kupwara", "Pulwama", "Shopian", "Srinagar"}));
                break;
            case "Jharkhand":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Bokaro", "Chatra", "Deoghar", "Dhanbad", "Dumka", "East Singhbhum", "Garhwa", "Giridih", "Godda", "Gumla", "Hazaribag", "Jamtara", "Khunti", "Koderma", "Latehar", "Lohardaga", "Pakur", "Palamu", "Ramgarh", "Ranchi", "Sahibganj", "Seraikelakharsawan", "Simdega", "West Singhbhum"}));
                break;
            case "Karnataka":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Bagalkot", "Bangalore Urban", "Bangalore Rural", "Belganum", "Ballari", "Bidar", "Bijapur", "Chamarajanagar", "Chikballapur", "Chikkamagaluru", "Chitradurga", "Dakshina Kannada", "Davanagere", "Dharwad", "Gadag", "Gulbarga", "Hassan", "Haveri", "Kodagu", "Kolar", "Koppal", "Mandya", "Mysore", "Raichur", "Ramanagara", "Shimoga", "Tumkur", "Udupi", "Uttara Kannada", "Yadgir"}));
                break;
            case "Kerala":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Alappuzha", "Ernakulam", "Idukki", "Kannur", "Kasaragod", "Kollam", "Kottayam", "Kozhikode", "Malappuram", "Palakkad", "Pathanamthitta", "Thiruvananthapuram", "Thissur", "Wayanad"}));
                break;
            case "Madhya Pradhesh":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Agar Malwa", "Alirajpur", "Anuppur", "Ashoknagar", "Balaghat", "Barwani", "Betul", "Bhind", "Bhopal", "Burhanpur", "Chhatarpur", "Chhindwara", "Damoh", "Datia", "Dewas", "Dhar", "Dindori", "Guna", "Gwalior", "Harda", "Hoshangabad", "Indore", "Jabalpur", "Jhabua", "Katni", "Khandwa", "Khargone", "Mandla", "Mandsaur", "Morena", "Narsinghpur", "Neemuch", "Panna", "Raisen", "Rajgarh", "Ratlam", "Rewa", "Sagar", "Satna", "Sehore", "Seoni", "Shahdol", "Shajapur", "Sheopur", "Shivpuri", "Sidhi", "Singrauli", "Tikamgarh", "Ujjain", "Umaria", "Vidisha"}));
                break;
            case "Maharashtra":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Ahmednagar", "Akola", "Amarvati", "Aurangabad", "Beed", "Bhandara", "Buldhana", "Chandrapur", "Dhule", "Gadchiroli", "Gondia", "Hingoli", "Jalgaon", "Jalna", "Kolhapur", "Latur", "Mumbai City", "Mumbai Suburban", "Nagpur", "Nanded", "Nandurbar", "Nashik", "Osmanabad", "Palghar", "Parbhani", "Pune", "Raigad", "Ratnagiri", "Sangli", "Satara", "Sindhudurg", "Solapur", "Thane", "Wardha", "Washim", "Yavatmal"}));
                break;
            case "Manipur":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Bishnupur", "Chandel", "Churachandpur", "Imphal-East", "Imphal-West", "Senapati", "Tamenglong", "Pherzawl", "Noney", "Kamjong", "Jiribam", "Kakching"}));
                break;
            case "Meghalaya":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "West Jaintia Hills", "East Jaintia Hills", "East Khasi Hills", "West Khasi Hills", "South West Khasi Hills", "Ri-Bhoi", "North Garo Hills", "East Garo Hills", "South Garo Hills", "West Garo Hills", "South West Garo Hills"}));
                break;
            case "Mizoram":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Aizawl", "Kolasib", "Lawngtlai", "Lunglei", "Mamit", "Saiha", "Serchhip", "Champhai", "Hnahthial", "Khawzawl", "Saitual"}));
                break;
            case "Nagaland":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Dimapur", "Kiphire", "Kohima", "Longleng", "Mokokchung", "Mon", "Peren", "Phek", "Tuensang", "Wokha", "Zunheboto"}));
                break;
            case "Odisha":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Angul", "Balangir", "Balasore", "Bargarh", "Bhadrak", "Boudh", "Cuttack", "Deogarh", "Dhenkanal", "Gajapati", "Ganjam", "Jagatsinghapur", "Jaipur", "Jharsuguda", "Kalahandhi", "Kandhamal", "Kendrapara", "Kendujhar", "Khordha", "Koraput", "Malkangiri", "Mayurbhanj", "Nabarangpur", "Nayagarh", "Nuapada", "Puri", "Rayagada", "Sambalpur", "Sonepur", "Sundargarh"}));
                break;
            case "Punjab":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Amritsar", "Barnala", "Bathinda", "Faridkot", "Fatehgarh Sahib", "Fazilka", "Ferozepur", "Gurdaspur", "Hoshiarpur", "Jalandhar", "Kapurthala", "Ludhiana", "Mansa", "Mogo", "Muktsar", "Nawanshahr", "Pathankot", "Patiala", "Rupnagar", "Sahibzada Ajit Singh Nagar", "Sangrur", "Tarn Taran"}));
                break;
            case "Rajasthan":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Ajmer", "Alwar", "Banaswara", "Baran", "Barmer", "Bharatpur", "Bhilwara", "Bikaner", "Bundi", "Chittorgarh", "Churu", "Dausa", "Dholpur", "Dungarpur", "Hanumangarh", "Jaipur", "Jaisalmer", "Jalore", "Jhalawar", "Jhunjhunu", "Jodhpur", "Karauli", "Kota", "Nagaur", "Pali", "Pratapgarh", "Rajsamand", "Sawai Madhopur", "Sikar", "Sirohi", "Sri Ganganagar", "Tonk", "Udaipur"}));
                break;
            case "Sikkim":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "East Sikkim", "North Sikkim", "South Sikkim", "West Sikkim"}));
                break;
            case "Tamil Nadu":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Ariyalur", "Chengalpattu", "Chennai", "Coimbatore", "Cuddalore", "Dharmapuri", "Erode", "Kallakurichi", "Kanchipuram", "Kanyakumari", "Karur", "Krishnagiri", "Madurai", "Nagapattinam", "Namakkal", "Nilgiris", "Perambalur", "Pudukkottai", "Ramanathapuraam", "Ranipet", "Salem", "Sivaganga", "Tenkasi", "Thanjavur", "Theni", "Thoothukudi", "Tiruchirappalli", "Tirunelveli", "Tirupathur", "Tiruppur", "Tiruvallur", "Tiruvannamalai", "Tiruvarur ", "Vellore", "Viluppuram", "Virudhunagar"}));
                break;
            case "Telangana":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Adilabad", "Bhandradri Kothagudem", "Hyderabad", "Jagitial", "Jangaon", "Jayashankar Bhupalpally", "Jogulamba Gadwal", "Kamareddy", "Karimnagar", "Khamman", "Komaram Bheem", "Mahabubabad", "Mahabubnagar", "Mancherial", "Medak", "Medchal Malkajgiri", "Mulugu", "Nagarkurnool", "Narayanpet", "Nalgonda", "Nirmal", "Nizamabad", "Peddapalli", "Rajanna sircilla", "Ranga Reddy", "Sanga Reddy", "Siddipet", "Suryapet", "Vikarabad", "Wanaparthy", "Warangal Rural", "Warangal Urban", "Yadadri Bhuvanagiri"}));
                break;
            case "Tripura":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Dhalai", "Sipahijala", "Khowai", "Gomati", "Unakoti", "North Tripura", "South Tripura", "West Tripura"}));
                break;
            case "Uttar Pradesh":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Agra", "Firozabad", "Mainpuri", "Mathura", "Aligarh", "Etah", "Hathras", "Kasganj", "Allahabad", "Fatehpur", "Kaushambi", "Pratapgarh", "Azamgarh", "Ballia", "Mau", "Budaum", "Bareilly", "Pilibhit", "Shahjahanpur", "Basti", "Sant Kabir Nagar", "Siddharthnagar", "Banda", "Chitrakoot", "Hamirpur", "Mahoba", "Bahraich", "Balarampur", "Gonda", "Shravasti", "Ambedkar Nagar", "Amethi", "Barabanki", "Faizabad", "Sultanpur", "Deoria", "Gorakhpur", "Kushinagar", "Maharajganj", "Jalaun", "Jhansi", "Lalitpur", "Auraiya", "Etawah", "Farrukhabad", "Kannauj", "Kanpur Dehat", "Kanpur Nagar", "Hardoi", "Lakhimpur Kheri", "Lucknow", "Raebareli", "Sitapur", "Unnao", "Bagpat", "Bulandshahr", "Gautam Buddha Nagar", "Ghaziabad", "Hapur", "Meerut", "Bhadohi", "Mirzapur", "Sonbhadra", "Amroha", "Bijnor", "Moradabad", "Rampur", "Sambhal", "Muzaffarnagar", "Saharanpur", "Shamli", "Chandauli", "Ghazipur", "Jaunpur", "Varanasi"}));
                break;
            case "Uttarakhand":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Almora", "Bageshwar", "Chamoli", "Champawat", "Dehradun", "Haridwar", "Nainital", "Pauri Garhwal", "Pithoragarh", "Rudraprayag", "Tehri Garhwal", "Udham Singh Nagar", "Uttarkashi"}));
                break;
            case "West Bengal":
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Alipurduar", "Bankura", "Birbhum", "Cooch Behar", "Dakshin Dinajpur", "Darjeeling", "Hooghly", "Howrah", "Jalpaiguri", "Jhargram", "Kalimpong", "Kolkata", "Malda", "Murshidabad", "Nadia", "North 24 parganas", "Paschim Medinipur", "Paschim Burdwan", "Purba Medinipur", "Purulia", "South 24 parganas", "Uttar Dinajpur"}));
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
        String state = jComboBox5.getSelectedItem().toString();
        if(null!=state)
            switch (state) {
            case "None":
                JOptionPane.showMessageDialog(null,"Please select a state");
                break;
            case "Andhra Pradesh":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Anantapur", "Chittoor", "East Godavari", "Guntur", "YSR Kadapa district", "Krishna", "Kurnool", "Nellore", "Prakasam", "Srikakulam", "Vishakhapatnam", "Vizianagaram", "West Godavari" }));
                break;
            case "Arunachal Pradesh":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Tawang", "West Kameng", "East Kameng", "Pakke-Kessang", "Papum Pare", "Kurung Kumey", "Kra Daadi", "Lower Subansiri", "Upper Subansiri", "West Siang", "Shi-Yomi", "East Siang", "Siang", "Upper Siang", "Lower Siang", "Lepa-Rada", "Lower Dibang Valley", "Dibang Valley", "Anjaw", "Lohit", "Namsai", "Changlang", "Tirap", "Longding", "Kamle" }));
                break;
            case "Assam":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Baksa", "Barpeta", "Biswanath", "Bongaigaon", "Cachar", "Charaideo", "Chirang", "Darrang", "Dhemaji", "Dhubri", "Dibrugarh", "Dima Hasao", "Goalpara", "Golaghat", "Hailakandi", "Hojai", "Jorhat", "Kamrup Metropolitan", "Kamrup", "Karbi Anglong", "Karimganj", "Kokrajhar", "Lakhimpur", "Majuli", "Morigaon", "Nagaon", "Nalbari", "Sivasagar", "Sonitpur", "South Salmara-Mankachar", "Tinsukia", "Udalguri", "West Karbi Anglong" }));
                break;
            case "Bihar":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Araria", "Arwal", "Aurangabad", "Banka", "Begusarai", "Bhagalpur", "Bhojpur", "buxar", "Darbhanga", "East Champaran", "Gaya", "Gopalganj", "Jamui", "Jehanabad", "Khagaria", "Kishanganj", "Kaimur", "Katihar", "Lakhisarai", "Madhubani", "Madhepura", "Muzaffarpur", "Nalanda", "Nawada", "Patna", "Purnia", "Rohtas", "Saharsa", "Samastipur", "Sheohar", "Sheikhpura", "Saran", "Sitamarhi", "Supaul", "Siwan", "Vaishali", "West Champaran" }));
                break;
            case "Chhattisgarh":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Bijapur", "sukma", "Dantewada", "Baster", "Kondagaon", "Narayanpur", "Kanker", "Kawardha", "Rajnandgaon", "Balod", "Durg", "Bemetara", "Raipur", "Baloda Bazar", "Mahasamund", "Bilaspur", "Mungeli", "Korba", "Janjgir-Champa", "Raigarh", "Jashpur", "Korea", "Surajpur", "Surguja", "Balrampur"}));
                break;
            case "Goa":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Bicholim", "Canocona", "Cunolim", "Curchorem", "Mapusa", "Margao", "Mormugao", "Panaji", "Pernem", "Ponda", "Quepem", "Sanguem", "Sanquelim", "Valpoi"}));
                break;
            case "Gujarat":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Ahmedabad", "Vadodara", "Anand", "Chhota udaipur", "Dahod", "Kheda", "Mahisagar", "Panchmahal", "Gandhinagar", "Aravalli", "Banaskantha", "Mehsana", "Patan", "Sabarkantha", "Rajkot", "Amreli", "Bhavanagar", "Botad", "Devbhoomi Dwarka", "Gir Somnath", "Jamnagar", "Junagadh", "Morbi", "Porbandar", "Surendranagar", "Kachchh"}));
                break;
            case "Haryana":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Ambala", "Bhiwani", "Charkhi Dhadri", "Faridabad", "Fatehabad", "Gurugram", "Hisar" , "Jhajjar", "Jind", "Kaithal", "Karnal", "Kurukshetra", "Mahendragarh", "Nuh", "Palwal", "Panchkula", "Panipat", "Rewari", "Rohtak", "Sirsa", "Sonipat", "Yamunanagar"}));
                break;
            case "Himachal Pradhesh":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Chamba", "Kangra", "Lahaul and Spiti", "Kullu", "Mandi", "Hamirpur", "Una", "Bilaspur", "Solan", "Sirmaur", "Shimla", "Kinnaur"}));
                break;
            case "Jammu and Kashmir":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Doda", "Jammu", "Kathua", "Kishtwar", "Poonch", "Rajouri", "Ramban", "Reasi", "Samba", "Udhampur", "Anantnag", "Bandipora", "Baramulla", "Budgam", "Ganderbal", "Kulgam", "Kupwara", "Pulwama", "Shopian", "Srinagar"}));
                break;
            case "Jharkhand":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Bokaro", "Chatra", "Deoghar", "Dhanbad", "Dumka", "East Singhbhum", "Garhwa", "Giridih", "Godda", "Gumla", "Hazaribag", "Jamtara", "Khunti", "Koderma", "Latehar", "Lohardaga", "Pakur", "Palamu", "Ramgarh", "Ranchi", "Sahibganj", "Seraikelakharsawan", "Simdega", "West Singhbhum"}));
                break;
            case "Karnataka":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Bagalkot", "Bangalore Urban", "Bangalore Rural", "Belganum", "Ballari", "Bidar", "Bijapur", "Chamarajanagar", "Chikballapur", "Chikkamagaluru", "Chitradurga", "Dakshina Kannada", "Davanagere", "Dharwad", "Gadag", "Gulbarga", "Hassan", "Haveri", "Kodagu", "Kolar", "Koppal", "Mandya", "Mysore", "Raichur", "Ramanagara", "Shimoga", "Tumkur", "Udupi", "Uttara Kannada", "Yadgir"}));
                break;
            case "Kerala":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Alappuzha", "Ernakulam", "Idukki", "Kannur", "Kasaragod", "Kollam", "Kottayam", "Kozhikode", "Malappuram", "Palakkad", "Pathanamthitta", "Thiruvananthapuram", "Thissur", "Wayanad"}));
                break;
            case "Madhya Pradhesh":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Agar Malwa", "Alirajpur", "Anuppur", "Ashoknagar", "Balaghat", "Barwani", "Betul", "Bhind", "Bhopal", "Burhanpur", "Chhatarpur", "Chhindwara", "Damoh", "Datia", "Dewas", "Dhar", "Dindori", "Guna", "Gwalior", "Harda", "Hoshangabad", "Indore", "Jabalpur", "Jhabua", "Katni", "Khandwa", "Khargone", "Mandla", "Mandsaur", "Morena", "Narsinghpur", "Neemuch", "Panna", "Raisen", "Rajgarh", "Ratlam", "Rewa", "Sagar", "Satna", "Sehore", "Seoni", "Shahdol", "Shajapur", "Sheopur", "Shivpuri", "Sidhi", "Singrauli", "Tikamgarh", "Ujjain", "Umaria", "Vidisha"}));
                break;
            case "Maharashtra":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Ahmednagar", "Akola", "Amarvati", "Aurangabad", "Beed", "Bhandara", "Buldhana", "Chandrapur", "Dhule", "Gadchiroli", "Gondia", "Hingoli", "Jalgaon", "Jalna", "Kolhapur", "Latur", "Mumbai City", "Mumbai Suburban", "Nagpur", "Nanded", "Nandurbar", "Nashik", "Osmanabad", "Palghar", "Parbhani", "Pune", "Raigad", "Ratnagiri", "Sangli", "Satara", "Sindhudurg", "Solapur", "Thane", "Wardha", "Washim", "Yavatmal"}));
                break;
            case "Manipur":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Bishnupur", "Chandel", "Churachandpur", "Imphal-East", "Imphal-West", "Senapati", "Tamenglong", "Pherzawl", "Noney", "Kamjong", "Jiribam", "Kakching"}));
                break;
            case "Meghalaya":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "West Jaintia Hills", "East Jaintia Hills", "East Khasi Hills", "West Khasi Hills", "South West Khasi Hills", "Ri-Bhoi", "North Garo Hills", "East Garo Hills", "South Garo Hills", "West Garo Hills", "South West Garo Hills"}));
                break;
            case "Mizoram":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Aizawl", "Kolasib", "Lawngtlai", "Lunglei", "Mamit", "Saiha", "Serchhip", "Champhai", "Hnahthial", "Khawzawl", "Saitual"}));
                break;
            case "Nagaland":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Dimapur", "Kiphire", "Kohima", "Longleng", "Mokokchung", "Mon", "Peren", "Phek", "Tuensang", "Wokha", "Zunheboto"}));
                break;
            case "Odisha":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Angul", "Balangir", "Balasore", "Bargarh", "Bhadrak", "Boudh", "Cuttack", "Deogarh", "Dhenkanal", "Gajapati", "Ganjam", "Jagatsinghapur", "Jaipur", "Jharsuguda", "Kalahandhi", "Kandhamal", "Kendrapara", "Kendujhar", "Khordha", "Koraput", "Malkangiri", "Mayurbhanj", "Nabarangpur", "Nayagarh", "Nuapada", "Puri", "Rayagada", "Sambalpur", "Sonepur", "Sundargarh"}));
                break;
            case "Punjab":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Amritsar", "Barnala", "Bathinda", "Faridkot", "Fatehgarh Sahib", "Fazilka", "Ferozepur", "Gurdaspur", "Hoshiarpur", "Jalandhar", "Kapurthala", "Ludhiana", "Mansa", "Mogo", "Muktsar", "Nawanshahr", "Pathankot", "Patiala", "Rupnagar", "Sahibzada Ajit Singh Nagar", "Sangrur", "Tarn Taran"}));
                break;
            case "Rajasthan":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Ajmer", "Alwar", "Banaswara", "Baran", "Barmer", "Bharatpur", "Bhilwara", "Bikaner", "Bundi", "Chittorgarh", "Churu", "Dausa", "Dholpur", "Dungarpur", "Hanumangarh", "Jaipur", "Jaisalmer", "Jalore", "Jhalawar", "Jhunjhunu", "Jodhpur", "Karauli", "Kota", "Nagaur", "Pali", "Pratapgarh", "Rajsamand", "Sawai Madhopur", "Sikar", "Sirohi", "Sri Ganganagar", "Tonk", "Udaipur"}));
                break;
            case "Sikkim":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "East Sikkim", "North Sikkim", "South Sikkim", "West Sikkim"}));
                break;
            case "Tamil Nadu":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Ariyalur", "Chengalpattu", "Chennai", "Coimbatore", "Cuddalore", "Dharmapuri", "Erode", "Kallakurichi", "Kanchipuram", "Kanyakumari", "Karur", "Krishnagiri", "Madurai", "Nagapattinam", "Namakkal", "Nilgiris", "Perambalur", "Pudukkottai", "Ramanathapuraam", "Ranipet", "Salem", "Sivaganga", "Tenkasi", "Thanjavur", "Theni", "Thoothukudi", "Tiruchirappalli", "Tirunelveli", "Tirupathur", "Tiruppur", "Tiruvallur", "Tiruvannamalai", "Tiruvarur ", "Vellore", "Viluppuram", "Virudhunagar"}));
                break;
            case "Telangana":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Adilabad", "Bhandradri Kothagudem", "Hyderabad", "Jagitial", "Jangaon", "Jayashankar Bhupalpally", "Jogulamba Gadwal", "Kamareddy", "Karimnagar", "Khamman", "Komaram Bheem", "Mahabubabad", "Mahabubnagar", "Mancherial", "Medak", "Medchal Malkajgiri", "Mulugu", "Nagarkurnool", "Narayanpet", "Nalgonda", "Nirmal", "Nizamabad", "Peddapalli", "Rajanna sircilla", "Ranga Reddy", "Sanga Reddy", "Siddipet", "Suryapet", "Vikarabad", "Wanaparthy", "Warangal Rural", "Warangal Urban", "Yadadri Bhuvanagiri"}));
                break;
            case "Tripura":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Dhalai", "Sipahijala", "Khowai", "Gomati", "Unakoti", "North Tripura", "South Tripura", "West Tripura"}));
                break;
            case "Uttar Pradesh":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Agra", "Firozabad", "Mainpuri", "Mathura", "Aligarh", "Etah", "Hathras", "Kasganj", "Allahabad", "Fatehpur", "Kaushambi", "Pratapgarh", "Azamgarh", "Ballia", "Mau", "Budaum", "Bareilly", "Pilibhit", "Shahjahanpur", "Basti", "Sant Kabir Nagar", "Siddharthnagar", "Banda", "Chitrakoot", "Hamirpur", "Mahoba", "Bahraich", "Balarampur", "Gonda", "Shravasti", "Ambedkar Nagar", "Amethi", "Barabanki", "Faizabad", "Sultanpur", "Deoria", "Gorakhpur", "Kushinagar", "Maharajganj", "Jalaun", "Jhansi", "Lalitpur", "Auraiya", "Etawah", "Farrukhabad", "Kannauj", "Kanpur Dehat", "Kanpur Nagar", "Hardoi", "Lakhimpur Kheri", "Lucknow", "Raebareli", "Sitapur", "Unnao", "Bagpat", "Bulandshahr", "Gautam Buddha Nagar", "Ghaziabad", "Hapur", "Meerut", "Bhadohi", "Mirzapur", "Sonbhadra", "Amroha", "Bijnor", "Moradabad", "Rampur", "Sambhal", "Muzaffarnagar", "Saharanpur", "Shamli", "Chandauli", "Ghazipur", "Jaunpur", "Varanasi"}));
                break;
            case "Uttarakhand":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Almora", "Bageshwar", "Chamoli", "Champawat", "Dehradun", "Haridwar", "Nainital", "Pauri Garhwal", "Pithoragarh", "Rudraprayag", "Tehri Garhwal", "Udham Singh Nagar", "Uttarkashi"}));
                break;
            case "West Bengal":
                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Alipurduar", "Bankura", "Birbhum", "Cooch Behar", "Dakshin Dinajpur", "Darjeeling", "Hooghly", "Howrah", "Jalpaiguri", "Jhargram", "Kalimpong", "Kolkata", "Malda", "Murshidabad", "Nadia", "North 24 parganas", "Paschim Medinipur", "Paschim Burdwan", "Purba Medinipur", "Purulia", "South 24 parganas", "Uttar Dinajpur"}));
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String FirstPreferenceCity=jComboBox2.getSelectedItem().toString();
        String SecondPreferenceCity=jComboBox4.getSelectedItem().toString();
        String ThirdPreferenceCity=jComboBox6.getSelectedItem().toString();
        String username=jLabel4.getText();
        
        if(FirstPreferenceCity=="None")
            JOptionPane.showMessageDialog(null,"Please select a city in first preference");
        
        if(SecondPreferenceCity=="None")
            JOptionPane.showMessageDialog(null,"Please select a city in second preference");
        
        if(ThirdPreferenceCity=="None")
            JOptionPane.showMessageDialog(null,"Please select a city in third preference");
        
        if(FirstPreferenceCity!="None" && SecondPreferenceCity!="None" && ThirdPreferenceCity!="None")
        {
            String FirstPreferState=(String)jComboBox1.getSelectedItem();
            String FirstPreferCity=(String)jComboBox2.getSelectedItem();
            String SecondPreferState=(String)jComboBox3.getSelectedItem();
            String SecondPreferCity=(String)jComboBox4.getSelectedItem();
            String ThirdPreferState=(String)jComboBox5.getSelectedItem();
            String ThirdPreferCity=(String)jComboBox6.getSelectedItem();
            try {
                File f=new File("C:\\Users\\Baruni Priya TS\\Documents\\NetBeansProjects\\Unit1,2,3,4,5\\src\\Mini_project\\Candidate_details.txt");
                FileWriter fw=new FileWriter(f,true);
                BufferedWriter bw=new BufferedWriter(fw);
                bw.write("First preferred state : "+FirstPreferState);
                bw.newLine();
                bw.write("First preferred city : "+FirstPreferCity);
                bw.newLine();
                bw.write("Second preferred state : "+SecondPreferState);
                bw.newLine();
                bw.write("Second preferred city : "+SecondPreferCity);
                bw.newLine();
                bw.write("Third preferred state : "+ThirdPreferState);
                bw.newLine();
                bw.write("Third preferred city : "+ThirdPreferCity);
                bw.newLine();
                bw.newLine();
                bw.close();
            } catch (IOException ex) {
                Logger.getLogger(City_selection.class.getName()).log(Level.SEVERE, null, ex);
            }
            new Terms_and_conditions(username,amount).setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(City_selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(City_selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(City_selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(City_selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new City_selection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
